name: trigger-api-generation
on:
  push:
    tags:
      - '*'
jobs:
  trigger-api-generation:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger API Generation Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: generate-api
          repo: k8s-client/api
          token: ${{ secrets.PERSONAL_TOKEN }}
          ref: master
